version: '3.1'

services:

  db:
    container_name: postgres_ctn
    image: postgres
    restart: always
    environment:
    ports: 
      - 5432:5432
    environment:
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: example_db

  adminer:
    container_name: adminer_ctn
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - 9090:8080